name: CI

on: [pull_request, push]

jobs:
  nodejs:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
    - name: setup nodejs
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: install tools
      run: npm ci
    - name: lint code
      run: npm run lint
    - name: format code
      run: |
        npm run format
        git diff --exit-code
    - name: markdown to handlebars
      run: npm run md2hbs
    - name: handlebars to html
      run: npm run hbs2html
    - name: generate final bundle
      run: npm run build
    - name: Deploy 🚀
      if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: dist # The folder the action should deploy.